import "@styles/globals.css";
import { Poppins } from "next/font/google";
import Nav from "@components/Nav";
import Footer from "@components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={poppins.className}>
        <Nav></Nav>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
